language: ruby
rvm: 2.0.0
env:
  - API_KEY=your_token IRKIT_CLIENT_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX IRKIT_DEVICE_ID=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX YO_API_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
